"""Bitcoin's RPC error codes."""
from __future__ import annotations

from enum import IntEnum


# https://github.com/bitcoin/bitcoin/blob/master/src/rpc/protocol.h#L23-L90
class RPCErrorCode(IntEnum):
    # Standard JSON-RPC 2.0 errors
    RPC_INVALID_REQUEST = -32600
    RPC_METHOD_NOT_FOUND = -32601
    RPC_INVALID_PARAMS = -32602
    RPC_INTERNAL_ERROR = -32603
    RPC_PARSE_ERROR = -32700

    # General application defined errors
    RPC_MISC_ERROR = -1
    RPC_TYPE_ERROR = -3
    RPC_INVALID_ADDRESS_OR_KEY = -5
    RPC_OUT_OF_MEMORY = -7
    RPC_INVALID_PARAMETER = -8
    RPC_DATABASE_ERROR = -20
    RPC_DESERIALIZATION_ERROR = -22
    RPC_VERIFY_ERROR = -25
    RPC_VERIFY_REJECTED = -26
    RPC_VERIFY_ALREADY_IN_CHAIN = -27
    RPC_IN_WARMUP = -28
    RPC_METHOD_DEPRECATED = -32

    # Aliases for backward compatibility
    RPC_TRANSACTION_ERROR = RPC_VERIFY_ERROR
    RPC_TRANSACTION_REJECTED = RPC_VERIFY_REJECTED
    RPC_TRANSACTION_ALREADY_IN_CHAIN = RPC_VERIFY_ALREADY_IN_CHAIN

    # P2P client errors
    RPC_CLIENT_NOT_CONNECTED = -9
    RPC_CLIENT_IN_INITIAL_DOWNLOAD = -10
    RPC_CLIENT_NODE_ALREADY_ADDED = -23
    RPC_CLIENT_NODE_NOT_ADDED = -24
    RPC_CLIENT_NODE_NOT_CONNECTED = -29
    RPC_CLIENT_INVALID_IP_OR_SUBNET = -30
    RPC_CLIENT_P2P_DISABLED = -31
    RPC_CLIENT_NODE_CAPACITY_REACHED = -34

    # Chain errors
    RPC_CLIENT_MEMPOOL_DISABLED = -33

    # Wallet errors
    RPC_WALLET_ERROR = -4
    RPC_WALLET_INSUFFICIENT_FUNDS = -6
    RPC_WALLET_INVALID_LABEL_NAME = -11
    RPC_WALLET_KEYPOOL_RAN_OUT = -12
    RPC_WALLET_UNLOCK_NEEDED = -13
    RPC_WALLET_PASSPHRASE_INCORRECT = -14
    RPC_WALLET_WRONG_ENC_STATE = -15
    RPC_WALLET_ENCRYPTION_FAILED = -16
    RPC_WALLET_ALREADY_UNLOCKED = -17
    RPC_WALLET_NOT_FOUND = -18
    RPC_WALLET_NOT_SPECIFIED = -19
    RPC_WALLET_ALREADY_LOADED = -35
    RPC_WALLET_ALREADY_EXISTS = -36

    # Backwards compatible aliases
    RPC_WALLET_INVALID_ACCOUNT_NAME = RPC_WALLET_INVALID_LABEL_NAME

    # Unused reserved codes
    RPC_FORBIDDEN_BY_SAFE_MODE = -2
